spring.application.name=pass-in
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/pass_in}
spring.datasource.username=${DATABASE_USERNAME:pass_in}
spring.datasource.password=${DATABASE_PASSWORD:pass_in}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

app.cors.allowed-origin=${FRONTEND_ORIGIN:http://localhost:9090}
